# version of docker composer sytanx
version: "3.9"



# commands is to run docker
services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
        - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    # to connect database
    environment:
      - DB_HOST=db # name of the db service
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    
    # tells to wait to db service
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# name of the volume
volumes:
  dev-db-data: